# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-05 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171204_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name=b'\xe5\x88\xa0\xe9\x99\xa4\xe6\xa0\x87\xe8\xae\xb0')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('updata_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('recipient_name', models.CharField(max_length=20, verbose_name='\u6536\u4ef6\u4eba')),
                ('recipient_addr', models.CharField(max_length=256, verbose_name='\u6536\u4ef6\u5730\u5740')),
                ('zip_code', models.CharField(max_length=6, verbose_name='\u90ae\u653f\u7f16\u7801')),
                ('recipient_phone', models.CharField(max_length=11, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('is_default', models.BooleanField(default=False, verbose_name='\u662f\u5426\u9ed8\u8ba4')),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Passport', verbose_name='\u8d26\u6237')),
            ],
            options={
                'db_table': 's_user_address',
            },
        ),
    ]
