# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-08 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        ('users', '0003_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name=b'\xe5\x88\xa0\xe9\x99\xa4\xe6\xa0\x87\xe8\xae\xb0')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('updata_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('show', models.BooleanField(default=True, verbose_name='\u663e\u793a\u8bc4\u8bba')),
                ('content', models.CharField(max_length=1000, verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Books')),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Passport')),
            ],
            options={
                'db_table': 's_comments',
            },
        ),
    ]
