# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-05 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name=b'\xe5\x88\xa0\xe9\x99\xa4\xe6\xa0\x87\xe8\xae\xb0')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('updata_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('type_id', models.SmallIntegerField(choices=[(1, b'Python'), (2, b'Javascript'), (3, b'\xe6\x95\xb0\xe6\x8d\xae\xe7\xbb\x93\xe6\x9e\x84\xe4\xb8\x8e\xe7\xae\x97\xe6\xb3\x95'), (4, b'\xe6\x9c\xba\xe5\x99\xa8\xe5\xad\xa6\xe4\xb9\xa0'), (5, b'\xe6\x93\x8d\xe4\xbd\x9c\xe7\xb3\xbb\xe7\xbb\x9f'), (6, b'\xe6\x95\xb0\xe6\x8d\xae\xe5\xba\x93')], default=1, verbose_name='\u5546\u54c1\u79cd\u7c7b')),
                ('name', models.CharField(max_length=20, verbose_name='\u5546\u54c1\u540d\u79f0')),
                ('desc', models.CharField(max_length=128, verbose_name='\u5546\u54c1\u7b80\u4ecb')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u5546\u54c1\u4ef7\u683c')),
                ('unite', models.CharField(max_length=20, verbose_name='\u5546\u54c1\u5355\u4f4d')),
                ('stock', models.IntegerField(default=1, verbose_name='\u5546\u54c1\u5e93\u5b58')),
                ('sales', models.IntegerField(default=0, verbose_name='\u5546\u54c1\u9500\u91cf')),
                ('detail', tinymce.models.HTMLField(verbose_name='\u5546\u54c1\u8be6\u60c5')),
                ('image', models.ImageField(upload_to='books', verbose_name='\u5546\u54c1\u56fe\u7247')),
                ('status', models.SmallIntegerField(choices=[(0, b'\xe4\xb8\x8b\xe7\xba\xbf'), (1, b'\xe4\xb8\x8a\xe7\xba\xbf')], default=1, verbose_name='\u5546\u54c1\u72b6\u6001')),
            ],
            options={
                'db_table': 's_books',
            },
        ),
    ]
